// This file was generated by running script/readme.rb

import React from "react";

import PageHeader from "./PageHeader";
import { RubyMarker, RubyTooltip, RubyTimeline } from "./RubyTimeline";
import { Timeline, TimelineTooltip, TimelineLine, TimelineEntry, TimelineEntryTooltip } from "./Timeline";

const App = () => (
  <div className="container">
    <PageHeader />
    <Timeline startDate={new Date(Date.UTC(1993, 0, 1))} endDate={new Date(Date.UTC(2021, 11, 31))}>
      <RubyTimeline>
        <RubyTooltip>
          <TimelineTooltip />
        </RubyTooltip>
        <TimelineLine>
<TimelineEntry date={new Date(Date.UTC(1994, 0, 7))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 0.06 <small>1994-01-07</small></h2>

<p>This is the earliest <a href="https://cache.ruby-lang.org/pub/ruby/1.0/ChangeLog-pre-alpha">changelog entry</a> that I could find that had an explicit version on it. At this point Ruby was still a very early idea and the syntax was changing rapidly.</p>

<h4 id="changelog">ChangeLog</h4>

<p>Fri Jan  7 15:23:20 1994  Yukihiro Matsumoto  (matz at nws119)</p>

<pre><code>{`* baseline - version 0.06.
`}</code></pre>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(1995, 4, 19))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 0.76 <small>1995-05-19</small></h2>

<p>The changelog here is still entirely Yukihiro Matsumoto. It’s been a year since the last entry on this timeline and a ton has changed. The choice of including <code>0.76</code> is somewhat arbitrary here. It’s just that <a href="https://cache.ruby-lang.org">https://cache.ruby-lang.org</a> happens to have a tar file containing that particular release.</p>

<p>There are some interesting things happening that are mentioned in the changelog below. <code>include</code> used to be a keyword, but there are a couple of keywords that at the moment are going through “methodization” which extracts them from the grammar and moves them into standard-library space. We can see here as well that hashes used to be called <code>Dict</code>. This was the version that included syntax for hash literals and array literals (array literals used to be initialized with braces, but that change here).</p>

<p>The ToDo file used to live in the root of the repository in these older versions. It’s an interesting artifact, as it offers a window into Matz’ thinking at the time. We can see in this version and many future versions he mentions heredocs (which do eventually get added before <code>1.0</code>) as well as a byte code interpreter (what would eventually become <code>YARV</code>).</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/0.76.txt">EBNF</a></li>
  <li><a href="diagrams/0.76.xhtml">Diagram</a></li>
</ul>

<h4 id="changelog">ChangeLog</h4>

<p>Wed Apr 26 09:50:56 1995  Yukihiro Matsumoto  (matz@ix-02)</p>

<pre><code>{`* parse.y: イテレータブロックの変数宣言を\`|'で括るようにした．これ
  でイテレータ変数がない時は宣言そのものを省略できる．文法の変更は
  久しぶりだ．
`}</code></pre>

<p>Mon Mar  6 19:34:32 1995  Yukihiro Matsumoto  (matz@ix-02)</p>

<pre><code>{`* eval.c(inlcude): メソッド化．動的にモジュールをインクルードでき
  るように．さらに任意のオブジェクトにもモジュールをインクルードで
  きるメソッド \`extend'も用意した．

* parse.y: 文法からincludeを削除．メソッド化．
`}</code></pre>

<p>Tue Feb 28 15:35:10 1995  Yukihiro Matsumoto  (matz@ix-02)</p>

<pre><code>{`* parse.y: 配列，連想配列の最後に\`,'をおけるように．
`}</code></pre>

<p>Fri Oct 14 13:22:18 1994  Yukihiro Matsumoto  (matz@ix-02)</p>

<pre><code>{`* version 0.52 released: ……なんてこったい.
`}</code></pre>

<p>Thu Jul 14 11:18:07 1994  Yukihiro Matsumoto  (matz@ix-02)</p>

<pre><code>{`* parse.y: Dictを生成する構文を追加. こちらを&#123;..&#125;にした.

* parse.y: 配列を生成する構文を[..]に変更した. 過去のRubyスクリプ
  トとの互換性が保てないが, Dictを生成する構文を導入するに当たり,
  perl5に合わせて(意識して), 変更する時期は今しかないと考えた. 
  *BACKWARD INCOMPATIBILITY*
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>format機能</li>
  <li>here document</li>
  <li>re-write regex code for speed</li>
  <li>byte code interpretor</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(1995, 11, 21))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 0.95 <small>1995-12-21</small></h2>

<p>This is also somewhat arbitrary, but the cache has an entry for it so I’m including it here. Technically the last pre-1.0 release was <code>0.99.4-961224</code>. Between this release and <code>1.0-961225</code>, it’s mostly cleanup and preparation. At this point there are some other contributors, including Jun Kuroda and Hirofumi Watanabe.</p>

<p>The changelog mentions some interesting syntax changes, including changing the <code>defined</code> keyword to include a <code>?</code> since this release now supports <code>?</code> and <code>!</code> at the end of method names. There’s also an amusing anecdote about how the <code>rescue</code> keyword used to be misspelled but that this release fixed the typo. Also included are the <code>not</code> operator, dynamic superclasses, and optional parentheses on method definition arguments, to just name a few.</p>

<p>At this point in the ToDo file we get the addition of an item that says <code>hand written parser (recursive descent)</code>. While this one didn’t end up being executed at any point (Ruby has stuck with the Bison parser generator the entire way through to today) it’s a very interesting thought even with today’s codebase.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/0.95.txt">EBNF</a></li>
  <li><a href="diagrams/0.95.xhtml">Diagram</a></li>
</ul>

<h4 id="changelog">ChangeLog</h4>

<p>Thu Nov  9 23:26:01 1995  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y (f_arglist): メソッド定義の引数を括弧で括らなくても良い
  ようにした．
`}</code></pre>

<p>Wed Nov  8 00:17:51 1995  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y: class文のsuperclass部を定数から式に拡張した．
`}</code></pre>

<p>Fri Sep  8 14:18:51 1995  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* ruby.texi: \`!', \`?'に対応してアップデート．

* parse.y: defined -&gt; defined?

* parse.y (yylex): 変数名の後ろに\`?'も許す．述語メソッドの後ろに
  \`?'を追加する．
`}</code></pre>

<p>Thu Sep  7 20:01:33 1995  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y: 変数名の後ろに\`!'を許す．
`}</code></pre>

<p>Mon Aug  7 12:47:41 1995  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y: resque -&gt; rescue．恥ずかしいがtypoを残しておくわけには
  いかないよなあ．なんで今まで気がつかなかったのか…．
`}</code></pre>

<p>Wed Jun  7 11:58:12 1995  Yukihiro Matsumoto  <a href="mailto:matz@ix-02">matz@ix-02</a></p>

<pre><code>{`* parse.y: not演算子の追加．優先順位の低い\`!'演算子．
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>Hand written parser(recursive decent)</li>
  <li>format機能</li>
  <li>here document</li>
  <li>re-write regex code for speed</li>
  <li>byte code interpretor</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(1996, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.0.961225 <small>1996-12-25</small></h2>

<p>This is the first public <code>1.0</code> release, released on Christmas of 1996. A couple of things change here since our last entry, most of which include changes that take it from looking like C++ to looking more like the Ruby we know today. For example, the operator that indicates a superclass in a class declaration changes from <code>:</code> to <code>&lt;</code>. Also, the <code>continue</code> keyword gets renamed to <code>next</code>. <code>rescue</code> also gets a boost in utility, as it can now capture the exception as a variable and can rescue multiple exceptions at once. There’s also a very short-lived triple-quoted string that exists for about 2 weeks in the codebase before Matz removed it.</p>

<p>The todo file contains some interesting entries at this point. Beyond the <code>format</code> function that has been on the list for a while, the regex item now gains the “and copyright” suffix. There’s also an entry for access control/packages. This is stil being discussed today, and various efforts have been made to accomplish this in Ruby-space outside of the runtime like <a href="https://github.com/Shopify/packwerk">packwerk</a>.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.0.961225.txt">EBNF</a></li>
  <li><a href="diagrams/1.0.961225.xhtml">Diagram</a></li>
</ul>

<h4 id="changelog">ChangeLog</h4>

<p>Thu Dec 12 00:41:17 1996  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y (parse_string): """..."""はやはり無くすことにした
`}</code></pre>

<p>Thu Nov 28 00:59:54 1996  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* version 0.99.3-961128

* parse.y (parse_string): 3-quote styleの文字列(例:"""abc"d"e""")
`}</code></pre>

<p>Thu Aug 29 10:49:40 1996  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y (expr): イテレータの新形式に「method do .. end」形式を採
  用した．もちろん昔の形式も有効．
`}</code></pre>

<p>Tue Aug 20 13:37:16 1996  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y (primary): rescueの構文を変更(同定引数の追加，複数rescue)
`}</code></pre>

<p>Thu Jul 25 12:15:04 1996  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y: break/next/redo/retryのメソッド化．

* parse.y (primary): unless/untilの復活
`}</code></pre>

<p>Wed May 22 19:48:42 1996  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y (superclass): スーパークラスの指定子を\`:'から\`&lt;'に変更．
`}</code></pre>

<p>Wed Mar 27 10:02:44 1996  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y: 予約語の変更 continue -&gt; next
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>パッケージまたは大域変数のアクセス制御</li>
  <li>format機能</li>
  <li>re-write regex code for speed and copyright</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(1997, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.0.971225 <small>1997-12-25</small></h2>

<p>Following in what would eventually become quite a transition, Matz released a new version of Ruby on Christmas 1997. It’s still <code>1.0</code> (this is not yet following semantic versioning) but the suffix has been updated to include the date.</p>

<p>There are a couple of interesting syntactical additions to the language during this time. Regular expressions get a couple of special flags that indicate the character encoding. Perhaps this is one of the best advantages of having this language be created outside of an English-speaking country: encoding was always at the forefront. While we wouldn’t get great encoding support until <code>1.9</code>, even having the option at this point is a win.</p>

<h4 id="changelog">ChangeLog</h4>

<p>Mon Apr  7 11:36:16 1997  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y (primary): syntax to access singleton class.
`}</code></pre>

<p>Thu Apr  3 02:12:31 1997  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y (parse_regx): new option //[nes] to specify character
  code for regexp literals.  Last specified code option is valid.
`}</code></pre>

<p>Tue Mar 25 14:08:43 1997  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y (expr): alias $var1 $var2 makes alias of the global
  variable. 
`}</code></pre>

<p>Fri Mar 14 14:36:28 1997  Yukihiro Matsumoto  <a href="mailto:matz@caelum.co.jp">matz@caelum.co.jp</a></p>

<pre><code>{`* parse.y (yylex): enables negative hex/octal numbers and \`_' in
  non-decimal numbers.
`}</code></pre>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(1998, 11, 24))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.3.0 <small>1998-12-24</small></h2>

<p>This is considered a “development” release, and is meant to be used as a branch for the core developers and not used in production. It is released one day before the “stable” <code>1.2.0</code> version. It includes a couple of syntactic additions that are then used for development over the course of the next year before they are included in the <code>1.4.0</code> stable version. They are:</p>

<ul>
  <li><em><code>begin..rescue..else..end</code> clauses</em><br />
<code>rescue</code> already existed, but this provided support for the <code>else</code> keyword in this chain in the case that no exception was raised</li>
  <li><em><code>&lt;&lt;-</code> indentable heredocs</em><br />
heredocs already existed, but you always had to put the ending at the beginning of the line; this change allowed the endings to be indented to the same indentation as the code</li>
  <li><em><code>::</code> method calls</em><br />
effectively an alias for the <code>.</code> operator, there was a convention for a while to call class-level methods with <code>::</code></li>
</ul>

<p>Also interesting to note in this version are 2 new entries in the todo file. The first is “named” arguments (what would eventually become keyword arguments). Though the syntax isn’t what ended up landing <code>:=</code> versus just <code>:</code>, it’s still interesting to see the entry all of the way back here.</p>

<p>Worth noting is the <code>objectify interpreters</code> entry. While I can’t speak to what this would actually look like, what it <em>could</em> be in reference to would be an object that could be accessed from Ruby-space that would accept an AST as an argument and be able to execute the code on demand. Extending this idea to include a reentrant parser, and Matz is effectively referring to the Rubinius project which would be started a little less than a decade later.</p>

<h4 id="changelog">ChangeLog</h4>

<p>Thu Dec 24 00:17:00 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (primary): enable expr::identifier as method
  invocation.
`}</code></pre>

<p>Mon Dec  7 22:08:22 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (primary): allows \`def obj::foo; .. end'.
`}</code></pre>

<p>Sat Dec  5 23:27:23 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (here_document): indentable here-doc delimiter by
  \`&lt;&lt;-'.  Proposed by Clemens &lt;c.hintze@gmx.net&gt;.  Thanks.
`}</code></pre>

<p>Mon Nov 16 23:26:29 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (primary): exec else clause if no exception raised.
`}</code></pre>

<p>Wed Oct 14 00:18:33 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (when_args): \`when a, *b' style new syntax for array
  expansion in \`case'.
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>package or access control for global variables</li>
  <li>named arguments like foo(nation:=”german”).</li>
  <li>multiple return values, yield values.  maybe imcompatible</li>
  <li>objectify interpreters</li>
  <li>syntax tree -&gt; bytecode ???</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(1998, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.2.0 <small>1998-12-25</small></h2>

<p>This is a “stable” release, and is meant for production. It’s the first stable release since <code>1.0</code> was released exactly 2 years prior. A lot of new syntax was introduced in those two years, many of which form the foundation of the kind of Ruby that was see today. Here are a couple of the standout entries:</p>

<ul>
  <li><em>heredocs</em><br />
easily one of the most difficult-to-parse syntax constructs gets introduced</li>
  <li><em><code>=begin</code> to <code>=end</code></em><br />
multi-line comments now were easier to manage</li>
  <li><em><code>true</code> and <code>false</code></em><br />
these keywords didn’t actually exist before this point</li>
  <li><em><code>BEGIN</code> and <code>END</code></em><br />
borrowing from awk, this syntax was very useful for scripts</li>
  <li><em><code>%w</code> word lists</em><br />
here we start to see the beginning of the <code>%</code>-lists syntax</li>
  <li><em>top-level constant access</em><br />
you could now prefix a constant with <code>::</code> from within a nested scope to access a top-level constant</li>
  <li><em>block arguments</em><br />
arguments that were themselves blocks would now resolve</li>
  <li><em><code>||=</code> and <code>&amp;&amp;=</code> operators</em><br />
this further extended the assignment operators with <code>||</code> and <code>&amp;&amp;</code> support</li>
</ul>

<p>You can see in the changelog that <code>__END__</code> is no longer a keyword with this release. Over time a lot of the keywords that we have today have flipped back and forth between being methods and being keywords, including <code>next</code> and <code>break</code> (for example).</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.2.1.txt">EBNF</a></li>
  <li><a href="diagrams/1.2.1.xhtml">Diagram</a></li>
</ul>

<h4 id="changelog">ChangeLog</h4>

<p>Wed Jun 24 02:18:57 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (mlhs): \`((a,b)),c = [[1,2]],3' assigns a=1,b=2,c=3.
`}</code></pre>

<p>Tue Jun 23 11:46:16 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (yylex): \`&amp;&amp;=' and \`||=' added.
`}</code></pre>

<p>Fri Jun 19 14:34:49 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (mlhs): nested multiple assignment.
`}</code></pre>

<p>Wed Apr 15 01:22:56 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (yylex): allow nested parenthesises.
`}</code></pre>

<p>Wed Mar  4 01:39:52 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (block_arg): new syntax - block argument in the
  calling arglist.
`}</code></pre>

<p>Thu Feb 26 17:22:13 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (fname): convert reswords into symbols.

* parse.y (reswords): reserved words are now embedded in the
 	  syntax (sigh).

* parse.y: now reserved words can be method names safely.
`}</code></pre>

<p>Fri Feb 20 10:17:51 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* version 1.1b8 released.

* parse.y (stmt): if/unless modifiers returns nil, if condition is 
  not established.
`}</code></pre>

<p>Tue Feb 17 00:04:32 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (yylex): new form \`::Const' to see toplevel constants.
`}</code></pre>

<p>Tue Jan 20 15:19:59 1998  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (terms): quoted word list by %w(a b c).
`}</code></pre>

<p>Fri Dec 12 00:50:25 1997  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (expr): BEGIN/END built in the syntax.
`}</code></pre>

<p>Thu Oct  9 11:17:50 1997  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (nextc): script parsing will be terminated by __END__ at
 	  beginning of line.

* eval.c (compile_error): \`__END__' is no longer a keyword.
`}</code></pre>

<p>Tue Sep 30 10:27:39 1997  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y: new keywords \`true' and \`false' added.
`}</code></pre>

<p>Wed Aug 27 11:32:42 1997  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* version 1.1 alpha3 released.

* parse.y (here_document): finally here document available now.
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>package or access control for global variables</li>
  <li>format</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(1999, 7, 13))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.4.0 <small>1999-08-13</small></h2>

<p>This is another stable release that follows a little less than a year after <code>1.2.0</code>. Not a huge amount changes with regard to syntax between the two versions, though there are lots of changes elsewhere in the codebase. The changes that were included were:</p>

<ul>
  <li><em>binary number literals</em><br />
you can now write number literals with the <code>0b</code> prefix</li>
  <li><em>anonymous <code>*</code> in method definitions</em><br />
you now don’t need to put an explicit name on splat arguments in method definitions</li>
  <li><em>nested string interpolation</em><br />
you used to not be able to do string interpolation within string interplation, but that was fixed here</li>
  <li><em>multibyte character identifiers</em><br />
there are now explicit multibyte character identifiers - this is more work toward supporting different encodings, but we won’t truly get there until <code>1.9</code></li>
</ul>

<p>The todo file got a lot longer in this version. Below is just a snippet that relates to parsing, but in reality there were multiple sections added. You can see entries that we already had like the packaging system, named arguments, and objectify interpreters. There are also some new entries like <code>class variable</code> (what ended up becoming <code>@@variable</code>), <code>method to retrieve argument information</code> (this could be referring to method calls, but I think it’s referring to method parameters on the declaration, which would eventually become <code>Method#parameters</code>), and <code>compile time string concatenation</code> (which we eventually get where <code>"foo" "bar"</code> becomes <code>"foobar"</code>).</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.4.0.txt">EBNF</a></li>
  <li><a href="diagrams/1.4.0.xhtml">Diagram</a></li>
</ul>

<h4 id="changelog">ChangeLog</h4>

<p>Thu Jun 24 19:11:29 1999  Yoshida Masato  <a href="mailto:yoshidam@yoshidam.net">yoshidam@yoshidam.net</a></p>

<pre><code>{`* parse.y (yylex): support multi-byte char identifiers.
`}</code></pre>

<p>Wed Jun 23 15:10:11 1999  Inaba Hiroto  <a href="mailto:inaba@sdd.tokyo-sc.toshiba.co.jp">inaba@sdd.tokyo-sc.toshiba.co.jp</a></p>

<pre><code>{`* parse.y (parse_regx): nested braces within #&#123;&#125; available.
`}</code></pre>

<p>Wed May 19 12:27:07 1999  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (f_rest_arg): allow just * for rest arg.

* parse.y (mlhs_basic): allow * without formal argument.
`}</code></pre>

<p>Fri Feb  5 22:11:08 1999  EGUCHI Osamu  <a href="mailto:eguchi@shizuokanet.ne.jp">eguchi@shizuokanet.ne.jp</a></p>

<pre><code>{`* parse.y (yylex): binary literal support, like 0b01001.

* parse.y (yylex): octal numbers can contain \`_'s.

* parse.y (yylex): now need at least one digit after prefix such
  as 0x, or 0b.

* bignum.c (rb_str2inum): recognize binary numbers like 0b0101.
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>compile time string concatenation, “hello” “world” =&gt; “helloworld”</li>
  <li>../… outside condition invokes operator method too.</li>
  <li>%w(a\ b\ c abc) =&gt; [“a b c”, “abc”]</li>
  <li>package or access control for global variables</li>
  <li>class variable (prefix?)</li>
  <li>named arguments like foo(nation:=”german”) or foo(nation: “german”).</li>
  <li>method to retrieve argument information (need new C API)</li>
  <li>multiple return values, yield values.  maybe incompatible ???</li>
  <li>cascading method invocation ???</li>
  <li>def Class#method .. end ??</li>
  <li>class Foo::Bar&lt;Baz .. end, module Boo::Bar .. end</li>
  <li>def Foo::Bar::baz() .. end ??</li>
  <li>objectify interpreters</li>
  <li>syntax tree -&gt; bytecode ???</li>
  <li>format like perl’s</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(1999, 11, 7))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.5.0 <small>1999-12-07</small></h2>

<p>Quickly following the release of <code>1.4.2</code> is the release of <code>1.5.0</code>. Not a ton of time has passed so there aren’t too many syntactical changes to mention. A couple of quick highlights though include <code>rescue</code> getting the additional modifier syntax like the conditionals and loops. We also get compile-time string concatenation (something that was listed in the todo from the previous version).</p>

<p>For the first time, the idea of <code>rescue</code> having a special <code>!!</code> operator is mentioned. This lives on in the todo file for quite a while. I’m not aware of if it was ever seriously considered.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.5.0.txt">EBNF</a></li>
  <li><a href="diagrams/1.5.0.xhtml">Diagram</a></li>
</ul>

<h4 id="changelog">ChangeLog</h4>

<p>Mon Nov  8 14:28:18 1999  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (stmt): rescue modifier added to the syntax.
`}</code></pre>

<p>Thu Oct 14 02:00:10 1999  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (string): compile time string concatenation.
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>def foo; .. rescue .. end</li>
  <li>compile time string concatenation, “hello” “world” =&gt; “helloworld”</li>
  <li>assignable constant, which now should be called shared variable.</li>
  <li>class variable (prefix?) – done by shared variable</li>
  <li>rescue modifier; a rescue b =&gt; begin a rescue; b end</li>
  <li>operator !! for  rescue.</li>
  <li>objectify symbols</li>
  <li>objectify characters</li>
  <li>../… outside condition invokes operator method too.</li>
  <li>… inside condition turns off just before right condition.???</li>
  <li>%w(a\ b\ c abc) =&gt; [“a b c”, “abc”]</li>
  <li>package or access control for global variables??</li>
  <li>named arguments like foo(nation:=”german”) or foo(nation: “german”).</li>
  <li>method to retrieve argument information (need new C API)</li>
  <li>multiple return values, yield values.  maybe incompatible ???</li>
  <li>cascading method invocation ???</li>
  <li>def Class#method .. end ??</li>
  <li>class Foo::Bar&lt;Baz .. end, module Boo::Bar .. end</li>
  <li>def Foo::Bar::baz() .. end ??</li>
  <li>RUBYOPT environment variable</li>
  <li>alias $defout $&gt;</li>
  <li>objectify interpreters</li>
  <li>syntax tree -&gt; bytecode ???</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2000, 8, 19))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.6.0 <small>2000-09-19</small></h2>

<p>A little over a year has passed since <code>1.4.0</code>, which means it’s time for another stable release. Only one big thing really changed with the syntax between the two versions, which is that <code>rescue</code> can now be used in the modifier form like the conditionals and loops.</p>

<p>Interestingly there are a couple of references to the flip-flop operator in the todo file. This has got to be one of the most controversial Ruby features. Later in <code>2.6</code> it will be deprecated, and then un-deprecated in <code>2.7</code>. Either way it’s definitely one of the more interesting syntactical constructs.</p>

<p>There’s also a mention of <code>0</code> being evaluated as falsy. Fortunately this one did not make it in, as that would have somewhat drastically changed the semantics of Ruby as we know it.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.6.0.txt">EBNF</a></li>
  <li><a href="diagrams/1.6.0.xhtml">Diagram</a></li>
</ul>

<h4 id="changelog">ChangeLog</h4>

<p>Mon Sep 11 14:24:47 2000  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (command_call): kYIELD moved to this rule to allow
  'a = yield b'. (ruby-bugs-ja:#PR15) 
`}</code></pre>

<p>Fri Sep  1 10:36:29 2000  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (aref_args,opt_call_args): add block_call to allow a
  method without parentheses and with block as a last argument.
`}</code></pre>

<p>Tue Jul 11 16:54:17 2000  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (yylex): \`@&lt;digit&gt;' is no longer a valid instance
  variable name.
`}</code></pre>

<p>Sat May  6 23:35:47 2000  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (lhs): should allow \`obj.Attr = 5' type expression.
`}</code></pre>

<p>Mon Jan 24 02:56:44 2000  Yukihiro Matsumoto  <a href="mailto:matz@netlab.co.jp">matz@netlab.co.jp</a></p>

<pre><code>{`* parse.y (yylex): -2.abs should be \`(-2).abs' to accomplish the
  principle of less surprise.  \`+2' too.
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>def foo; .. rescue .. end</li>
  <li>rescue modifier; a rescue b =&gt; begin a rescue; b end</li>
  <li>%w(a\ b\ c abc) =&gt; [“a b c”, “abc”]</li>
  <li>class variable (prefix @@)</li>
  <li>rescue RuntimeError =&gt; err</li>
  <li>operator !! for rescue. ???</li>
  <li>objectify characters</li>
  <li>../… outside condition invokes operator method too.</li>
  <li>… inside condition turns off just before right condition.???</li>
  <li>package or access control for global variables??</li>
  <li>named arguments like foo(nation:=”german”) or foo(nation: “german”).</li>
  <li>multiple return values, yield values.  maybe incompatible ???</li>
  <li>cascading method invocation ???</li>
  <li>def Class#method .. end ??</li>
  <li>class Foo::Bar&lt;Baz .. end, module Boo::Bar .. end</li>
  <li>def Foo::Bar::baz() .. end ??</li>
  <li>Fixnum 0 as false ????</li>
  <li>non confusing in-block local variable (is it possible?)
    <ul>
      <li>remove scope by block</li>
      <li>variables appears within block may have independent values.</li>
    </ul>
  </li>
  <li>alias $defout $&gt;</li>
  <li>objectify interpreters ???</li>
  <li>syntax tree -&gt; bytecode ???</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2000, 9, 1))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>nodeDump 0.1.0 <small>2000-10-01</small></h2>

<p>Following the release of Ruby <code>1.6</code>, Dave Thomas created the <a href="http://web.archive.org/web/20010302133702/http://www.pragmaticprogrammer.com:80/ruby/downloads/nodeDump.html">nodeDump</a> project. It walked the AST that Ruby generated after parsing and dumped out human-readable documentation about what Ruby would be evaluating. This ended up inspiring a bunch of other projects, and to my knowledge is the first real attempt at accessing and manipulating the AST outside of the core Ruby developers.</p>

<p>When this is released there is also mention of the <code>ii</code> project by Guy Decoux, but for whatever reason that appears to be lost to internet history (it was hosted on an ftp server that is no longer live).</p>

<p>This project and the many others that it inspired live on until <code>1.9</code> when CRuby switched over to the <code>YARV</code> bytecode interpreter. Because a lot of internals had to change to support that switch, most of the projects from around this time no longer functioned on the newer Ruby versions.</p>

<h4 id="links">Links</h4>

<ul>
  <li><a href="projects/nodeDump/README.txt">README</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2001, 0, 10))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>ruth 0.0.1 <small>2001-01-10</small></h2>

<p>A little while after <code>nodeDump</code> is released, Robert Feldt creates <a href="https://sourceforge.net/projects/rubyvm/files/ruth/">ruth</a> (short for Ruby under the hood). It is effectively a generalized form of the <code>nodeDump</code> utility, and provides two Ruby-space methods, <code>Ruby::Interpreter.parse</code> and <code>Ruby::Interpreter.method_body</code>. These return something that is akin to s-expressions that can then be manipulated. As with <code>nodeDump</code>, it’s a C extension that parses <code>node.h</code> to generate all of the necessary metadata.</p>

<h4 id="links">Links</h4>

<ul>
  <li><a href="projects/ruth/readme.txt">readme</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2001, 5, 1))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.7.1 <small>2001-06-01</small></h2>

<p>About a year has passed since <code>1.6</code> was released, and Ruby is starting to pick up a little steam. It’s also starting to look more and more like the Ruby that folks use today. You probably won’t see any <code>1.7</code> code the wild any more, but it’s possible you might get a glimse of <code>1.8</code>. Syntactically, a couple of things have been merged:</p>

<p>The <code>break</code> and <code>next</code> keywords now accept values. This becomes useful for methods like <code>detect</code>/<code>find</code> to controls the output of the overall loop. <code>%w</code> also gains the ability to escape spaces within the bounds, which was previously on the todo list. Finally, <code>rescue</code> can be added to singleton method bodies.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.7.1.txt">EBNF</a></li>
  <li><a href="diagrams/1.7.1.xhtml">Diagram</a></li>
</ul>

<h4 id="changelog">ChangeLog</h4>

<p>Tue May 22 02:37:45 2001  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (expr): "break" and "next" to take optional expression,
  which is used as a value for termination. [new, experimental]
`}</code></pre>

<p>Tue Mar  6 10:50:29 2001  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (primary): rescue and ensure clauses should be allowed
  to appear in singleton method body.
`}</code></pre>

<p>Wed Feb  7 16:05:22 2001  Nobuyoshi Nakada  <a href="mailto:nobu.nakada@nifty.ne.jp">nobu.nakada@nifty.ne.jp</a></p>

<pre><code>{`* parse.y (parse_quotedwords): %w should allow parenthesis escape.
`}</code></pre>

<p>Sat Dec  2 22:32:43 2000  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (stmt): multiple right hand side for single assignment
  (e.g. a = 1,2) is allowed.
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>operator !! for rescue. ???</li>
  <li>objectify characters</li>
  <li>../… outside condition invokes operator method too.</li>
  <li>… inside condition turns off just before right condition.???</li>
  <li>package or access control for global variables??</li>
  <li>named arguments like foo(nation:=”german”) or foo(nation: “german”).</li>
  <li>method to retrieve argument information (needs new C API)</li>
  <li>multiple return values, yield values.  maybe incompatible ???</li>
  <li>cascading method invocation ???</li>
  <li>def Class#method .. end ??</li>
  <li>class Foo::Bar&lt;Baz .. end, module Boo::Bar .. end</li>
  <li>def Foo::Bar::baz() .. end ??</li>
  <li>I18N (or M17N) script/string/regexp</li>
  <li>Fixnum 0 as false ????</li>
  <li>discourage use of symbol variables (e.g. $/, etc.) in manual</li>
  <li>discourage use of Perlish features by giving warnings.</li>
  <li>non confusing in-block local variable (is it possible?)
    <ul>
      <li>remove scope by block</li>
      <li>variables appears within block may have independent values.</li>
    </ul>
  </li>
  <li>decide whether begin with rescue or ensure make do..while loop.</li>
  <li>a +1 to be a+1, not a(+1).</li>
  <li>raise exception by \`\` error</li>
  <li>jar like combined library package.</li>
  <li>objectify interpreters ???</li>
  <li>syntax tree -&gt; bytecode ???</li>
  <li>Built-in Interactive Ruby.</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2001, 8, 10))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>JRuby <small>2001-09-10</small></h2>

<p>In 2001, Jan Arne Petersen began work on a reimplementation of Ruby for the Java Virtual Machine that was a direct port of the Ruby <code>1.6</code> code in Java called <a href="https://github.com/jruby/jruby">JRuby</a>. JRuby has undergone significant effort and change over the years. The parser itself has served as the basis for other Java projects to get their start as well, including TruffleRuby. Part of their efforts also involved reimplementing a lot of the standard library in Ruby itself, which also aided Rubinius and other projects.</p>

<h4 id="projects">Projects</h4>

<p>In addition to helping other projects along with their reimplementation efforts, JRuby also served as the parser basis for <a href="https://projekter.aau.dk/projekter/files/61071016/1181807983.pdf">ecstatic</a>, a type system research project.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2001, 9, 20))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>ripper 0.0.1 <small>2001-10-20</small></h2>

<p>Following on the heels of the release of Ruby <code>1.7</code>, Minero Aoki releases <a href="https://i.loveruby.net/archive/ripper/">ripper</a>, an event-driver Ruby parser. This is, to date, the most complete alternative Ruby parser, and boasts the ability to provide an entire AST or just a small subset. It functions by taking the <code>parse.y</code> from Ruby and modifying the actions. (This is the approach that almost every alternative implementation to CRuby ends up taking, as it’s extremely difficult to replicate the exact parsing behavior without a copy of the grammar file.)</p>

<p>Ripper is one of the few projects of this era to survive the <code>1.8</code> to <code>1.9</code> migration, likely because Aoki was a core contributor and made sure it additionally worked on the <code>YARV</code> branch. Eventually this project would become the way that many other projects retreived AST information, though it was always marked as “experimental”. Even today the README for ripper says <code>Ripper is still early-alpha version.</code>.</p>

<h4 id="projects">Projects</h4>

<p>Even though ripper has always been marked as <code>"experimental"</code>, a number of projects rely on it for accessing the parse tree. They’ve mostly been using it since it got merged into trunk with <code>1.9</code>. Those projects include:</p>

<ul>
  <li><a href="https://github.com/square/cane">cane</a> - a linter</li>
  <li><a href="https://github.com/mtsmfm/language_server-ruby">language_server-ruby</a> - a language server</li>
  <li><a href="https://github.com/prettier/plugin-ruby">prettier</a> - a formatter</li>
  <li><a href="https://github.com/penelopezone/rubyfmt">rubyfmt</a> - a formatter</li>
  <li><a href="https://github.com/ruby-formatter/rufo">rufo</a> - a formatter</li>
  <li><a href="https://github.com/makaroni4/sandi_meter">sandi_meter</a> - a linter</li>
  <li><a href="https://github.com/lsegal/yard">yard</a> - a documentation generator</li>
</ul>

<h4 id="links">Links</h4>

<ul>
  <li><a href="projects/ripper/readme.txt">readme</a></li>
  <li><a href="projects/ripper/sample/comment.rb.txt">sample/comment.rb</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2002, 9, 9))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>MetaRuby 0.7.0 <small>2002-10-09</small></h2>

<p><a href="http://artengine.ca/matju/MetaRuby/">MetaRuby</a> is a pretty interesting project that Mathieu Bouchard started around the Ruby 1.7 era. It was an attempt to implement a lot of the Ruby standard library in pure Ruby, predating the Rubinius project by a while. The reason I’m including it in this list is that in version <code>0.7.0</code>, MetaRuby included <code>RubySchema.rb</code>, which was a method of validating the shape of the Ruby abstract syntax tree.</p>

<h4 id="links">Links</h4>

<ul>
  <li><a href="projects/MetaRuby/Overview.txt">Overview</a></li>
  <li><a href="projects/MetaRuby/RubySchema.rb.txt">RubySchema.rb</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2003, 7, 4))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.8.0 <small>2003-08-04</small></h2>

<p>A lot happens between <code>1.7</code> and <code>1.8</code>. It’s been 2 years since the <code>1.7</code> release, and Ruby has started to pick up in popularity. The popular “pickaxe” book <code>Programming Ruby</code> (Andy Hunt, Chad Fowler, and Dave Thomas) was released in 2001, which helped spread Ruby even further outside of Japan. Later that year in October, the first international Ruby conference was held in Tampa, Florida. From there, Ruby Central was founded by Chad Fowler and David Black. All of this momentum helped push a lot of companies to start to try out Ruby for the first time, including 37Signals.</p>

<p>Syntactically, there are a couple of notable changes, including:</p>

<ul>
  <li><em><code>%W</code> word lists with interpolation</em><br />
much like <code>%q</code> and <code>%Q</code>, <code>%W</code> is created as the word-list version that supports interpolation</li>
  <li><em>dynamic symbols</em><br />
symbols can now be created with interpolation</li>
  <li><em><code>break</code> and <code>next</code> take values</em><br />
this becomes useful for methods like <code>detect</code>/<code>find</code> to controls the output of the overall loop</li>
  <li><em>nested constant assignment</em><br />
you can now assign the constants multiple levels deep using the <code>::</code> operator</li>
</ul>

<p><code>%w</code> also gains the ability to escape spaces within the bounds, which was previously on the todo list. <code>rescue</code> can additionally be added to class and module bodies, where previously it was only on method definitions.</p>

<p>The todo list includes a couple of interesting new additions. There’s mention of in-block local variables and the scoping they acquire. This would be addressed in <code>1.9</code>. There’s also mention of attempting to discourage folks from calling methods without parentheses. To my knowledge no linter currently exists for Ruby, but this would probably be the first rule if one did.</p>

<p>Finally, there’s the first explicit mention in the todo file of a parser API. Other tools have already started to crop up outside of core Ruby (like <code>ripper</code>) that give direct access to the <code>NODE</code> syntax tree structs, and with the increase in popularity the demand for these kinds of tools has only grown. This is the last minor version that did not ship with a first-class parser API, as <code>ripper</code> would be merged in <code>1.9</code>.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.8.0.txt">EBNF</a></li>
  <li><a href="diagrams/1.8.0.xhtml">Diagram</a></li>
</ul>

<h4 id="changelog">ChangeLog</h4>

<p>Thu Feb 20 10:11:30 2003  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (clhs): allow "Foo::Bar = x".
`}</code></pre>

<p>Wed Feb  5 17:11:02 2003  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (yylex): no .&lt;digit&gt; float literal anymore.
`}</code></pre>

<p>Mon Nov  4 16:49:14 2002  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (primary): allow 'when'-less case statement; persuaded
  by Sean Chittenden.
`}</code></pre>

<p>Fri Oct 18 23:11:21 2002  Nobuyoshi Nakada  <a href="mailto:nobu.nokada@softhome.net">nobu.nokada@softhome.net</a></p>

<pre><code>{`* parse.y (value_expr0): allow return/break/next/redo/retry in rhs
  of logical operator.  [ruby-dev:18534]
`}</code></pre>

<p>Fri Oct 11 15:58:06 2002  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (arg): rescue modifier is now an operator with
  precedence right below assignments. i.e. "a = b rescue c" now
  parsed as "a = (b rescue c)", not as "(a = b) rescue c". [new]
  [experimental]
`}</code></pre>

<p>Fri Jul 19 10:52:32 2002  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (yylex): new decimal notation '0d4567'.
`}</code></pre>

<p>Sat Jun 15 22:56:37 2002  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (yylex): obsolete '?&lt;whitespace&gt;'; use '?\\s', '?\\n',
  etc, instead.
`}</code></pre>

<p>Tue May 28 14:07:00 2002  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (arg): no more ugly hack for "**", so that "-2**2" to be
  parsed as "(-2)**2", whereas "- 2**2" or "-(2)**2" to be parsed
  as "-(2**2)".

* parse.y (yylex): '-2' to be literal fixnum. [new]
`}</code></pre>

<p>Tue Mar 26 01:56:33 2002  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (primary): while/until statement modifiers to "begin"
  statement now work as "do .. while" even when begin statement
  has "rescue" or "ensure" [new].

* parse.y (bodystmt): rescue/ensure is allowed at every bodies,
  i.e. method bodies, begin bodies, class bodies[new], and module
  bodies[new].
`}</code></pre>

<p>Wed Aug 29 02:18:53 2001  Yukihiro Matsumoto  <a href="mailto:matz@ruby-lang.org">matz@ruby-lang.org</a></p>

<pre><code>{`* parse.y (yylex): ternary ? can be followed by newline.
`}</code></pre>

<h4 id="todo">ToDo</h4>

<ul>
  <li>class Foo::Bar&lt;Baz .. end, module Boo::Bar .. end</li>
  <li>operator !! for rescue. ???</li>
  <li>objectify characters</li>
  <li>../… outside condition invokes operator method too.</li>
  <li>… inside condition turns off just before right condition.???</li>
  <li>package or access control for global variables??</li>
  <li>named arguments like foo(nation:=”german”) or foo(nation: “german”).</li>
  <li>method to retrieve argument information (needs new C API)</li>
  <li>multiple return values, yield values.  maybe incompatible ???</li>
  <li>cascading method invocation ???</li>
  <li>def Class#method .. end ??</li>
  <li>def Foo::Bar::baz() .. end ??</li>
  <li>Fixnum 0 as false ????</li>
  <li>non confusing in-block local variable (is it possible?)
    <ul>
      <li>remove scope by block</li>
      <li>variables appears within block may have independent values.</li>
    </ul>
  </li>
  <li>method combination, e.g. before, after, around, etc.</li>
  <li>“in” modifier, to annotate, or to encourage assertion.</li>
  <li>private instance variable (as in Python?) @_foo in class Foo =&gt; @_Foo_foo</li>
  <li>warn/error “bare word” method, like “foo”,  you should type “foo()”</li>
  <li>:symbol =&gt; value hash in the form of &#123;symbol: value, …&#125; ??</li>
  <li>objectify interpreters ???</li>
  <li>syntax tree -&gt; bytecode ???</li>
  <li>Parser API</li>
  <li>trap every method invocation, which can be enabled by e.g. trap_call :method.</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2004, 10, 10))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>ParseTree 1.0.0 <small>2004-11-10</small></h2>

<p>A little over a year after the release of <code>1.8</code>, Ryan Davis released <a href="https://github.com/seattlerb/parsetree">ParseTree</a>. It used internals specific to <code>1.8</code> to build out s-expressions that you could programmatically access. Interestingly it was tested against all of the available gems at the time it was written with a tool called <code>gauntlet</code>.</p>

<h4 id="links">Links</h4>

<ul>
  <li><a href="projects/parsetree/README.txt">README.txt</a></li>
  <li><a href="projects/parsetree/lib/gauntlet_parsetree.rb.txt">lib/gauntlet_parsetree.rb</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2006, 5, 5))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>RubyNode 0.1.0 <small>2006-06-05</small></h2>

<p>Still in the Ruby <code>1.8</code> to <code>1.9</code> timeline, Dominik Bathon released <a href="https://web.archive.org/web/20060630155424/http://rubynode.rubyforge.org/">RubyNode</a>. It was similar in spirit to <code>ParseTree</code>, except that it returns hashes of options on arrays and generally sticks a little closer to the internal node structure.</p>

<h4 id="links">Links</h4>

<ul>
  <li><a href="projects/rubynode/README.txt">README.txt</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2006, 6, 12))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Rubinius <small>2006-07-12</small></h2>

<p>Following work he had done to create a reentrant Ruby parser and a book he had read on bytecode interpreters, Evan Phoenix began working on a Ruby-in-Ruby implementation that he called <a href="https://github.com/rubinius/rubinius">Rubinius</a>. It took the <code>parse.y</code> of core Ruby and rewrote the actions to do things in the Ruby space. This actually went back and forth a bit between being implemented partly in C and partly in Ruby.</p>

<h4 id="projects">Projects</h4>

<ul>
  <li><a href="https://github.com/carlosbrando/melbourne">melbourne</a> - Rubinius’s parser distributed as a gem</li>
  <li><a href="https://github.com/codegram/pelusa">pelusa</a> - a linter that used the Rubinius infrastructure</li>
  <li><a href="https://rubygems.org/gems/sydparse">sydparse</a> - a reentrant Ruby parser that ended up being the basis of the Rubinius project</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2006, 6, 16))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Cardinal <small>2006-07-16</small></h2>

<p>Back in the Ruby <code>1.8</code> days, there was an interesting reimplementation of Ruby on the Parrot VM called <a href="https://github.com/parrot/cardinal">Cardinal</a>. This was one of the only attempts to reimplement Ruby that did not take the <code>parse.y</code> source and reengineer it. Instead it took the EBNF documentation from Ruby <code>1.6</code> and created its own PGE grammar.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2007, 3, 30))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>IronRuby <small>2007-04-30</small></h2>

<p>Around the time that interest in Ruby implementations was starting to take off, Microsoft decided to invest in a Ruby implementation on the .NET framework called <a href="http://www.wilcob.com/Wilco/IronRuby/microsoft_ironruby.aspx">IronRuby</a>. John Lam and the DLR Design Team worked on it for 3 years to make it able to run production workloads. Unfortunately in July 2010 Microsoft stopped funding the project, and ended up publishing it in 2011.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2007, 10, 14))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>ruby_parser 1.0.0 <small>2007-11-14</small></h2>

<p>Just before <code>1.9</code> was released, Ryan Davis created a spiritual sequel to <code>ParseTree</code> that would function running with the <code>1.9</code> branch. He took the <code>parse.y</code> file from core Ruby and rewrote the actions to be pure Ruby before piping it through <code>racc</code>. This was a similar idea to <code>ripper</code>, except that it was in Ruby instead of C.</p>

<h4 id="links">Links</h4>

<p><a href="projects/ruby_parser/lib/ruby_parser.y.txt">lib/ruby_parser.y</a></p>

<h4 id="projects">Projects</h4>

<p>A number of projects use <code>ruby_parser</code> as a way of accessing the syntax tree. Most of these were similarly created by Ryan Davis, but some others exist as well. Those include:</p>

<ul>
  <li><a href="https://github.com/thesp0nge/dawnscanner">dawnscanner</a> - a security analyzer</li>
  <li><a href="https://github.com/seattlerb/debride">debride</a> - an unused code analyzer</li>
  <li><a href="https://github.com/DamirSvrtan/fasterer">fasterer</a> - a performance linter</li>
  <li><a href="https://github.com/seattlerb/flay">flay</a> - a code similarity analyzer</li>
  <li><a href="https://github.com/seattlerb/flog">flog</a> - a code understandability analyzer</li>
  <li><a href="https://github.com/david-a-wheeler/railroader">railroader</a> - a static security analyzer</li>
  <li><a href="https://github.com/roodi/roodi">roodi</a> - a linter</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2007, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.9.0 <small>2007-12-25</small></h2>

<p>Ruby <code>1.9.0</code> was a very large change because it integrated Koichi Sasada’s graduate thesis <a href="http://www.atdot.net/yarv/oopsla2005eabstract-rc1.pdf">YARV</a> which stands for yet another RubyVM. It switched from being a tree-walk algorithm that kept an abstract syntax tree around to manipulate to being a bytecode interpreter that kept around instruction sequences.</p>

<p>In addition, while this transition was being made, <a href="https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?view=revision&amp;revision=6891"><code>ripper</code> was merged</a> into trunk. Now instead of forking <code>parse.y</code> and maintaining its own grammar, it instead was integrated into the main Ruby <code>parse.y</code>. In introduced a special comment format that lived inside the grammar actions that functioned as an alternate action that should be taken in the case that <code>ripper</code> was being built. Mostly it “dispatched” events when those tree nodes were being reduced and then continued building the tree.</p>

<p>There were a couple of additional (somewhat controversial) syntactical additions to the language with this version as well. Those include lambda literals (as in <code>-&gt; (foo) &#123; foo * 2 &#125;</code>) and symbol hash keys (as in <code>&#123; foo: "bar" &#125;</code>). To this day there are folks that will avoid both of those syntax constructs.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.9.0.txt">EBNF</a></li>
  <li><a href="diagrams/1.9.0.xhtml">Diagram</a></li>
</ul>

<h4 id="todo">ToDo</h4>

<ul>
  <li>class Foo::Bar&lt;Baz .. end, module Boo::Bar .. end</li>
  <li>raise exception by \`\` error</li>
  <li>clarify evaluation order of operator argument (=~, .., …)</li>
  <li>:symbol =&gt; value hash in the form of &#123;symbol: value, …&#125; ??</li>
  <li>operator !! for rescue. ???</li>
  <li>objectify characters</li>
  <li>../… outside condition invokes operator method too.</li>
  <li>… inside condition turns off just before right condition.???</li>
  <li>package or access control for global variables??</li>
  <li>named arguments like foo(nation:=”german”) or foo(nation: “german”).</li>
  <li>method to retrieve argument information (needs new C API)</li>
  <li>multiple return values, yield values.  maybe incompatible ???</li>
  <li>cascading method invocation ???</li>
  <li>def Class#method .. end ??</li>
  <li>def Foo::Bar::baz() .. end ??</li>
  <li>discourage use of symbol variables (e.g. $/, etc.) in manual</li>
  <li>discourage use of Perlish features by giving warnings.</li>
  <li>decide whether begin with rescue or ensure make do..while loop.</li>
  <li>method combination, e.g. before, after, around, etc.</li>
  <li>.. or something like defadvice in Emacs.</li>
  <li>property - for methods, or for objects in general.</li>
  <li>“in” modifier, to annotate, or to encourage assertion.</li>
  <li>selector namespace - something like generic-flet in CLOS, to help RubyBehavior</li>
  <li>private instance variable (as in Python?) @_foo in class Foo =&gt; @_Foo_foo</li>
  <li>warn/error “bare word” method, like “foo”,  you should type “foo()”</li>
  <li>objectify interpreters ???</li>
  <li>MicroRuby</li>
  <li>Built-in Interactive Ruby.</li>
  <li>Parser API</li>
  <li>Ruby module – Ruby::Version, Ruby::Interpreter</li>
</ul>

<h4 id="projects">Projects</h4>

<p>Although it was meant for testing, various projects have cropped up that have used <code>RubyVM::AbstractSyntaxTree</code> to access the Ruby parse tree. The biggest one worth mentioning is <a href="https://github.com/castwide/solargraph">solargraph</a>, a Ruby language server.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2008, 2, 13))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>MacRuby <small>2008-03-13</small></h2>

<p>In 2008, Laurent Sansonetti began work on MacRuby, a Ruby <code>1.9</code> implementation that targetted the LLVM compiler infrastructure. It supported ahead-of-time and just-in-time compilation. It similarly took the <code>parse.y</code> and massaged it a bit. Fortunately, because it was written mostly in Objective-C, it could keep most of it in place because the actions were already written in C.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2009, 0, 30))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.9.1 <small>2009-01-30</small></h2>

<p>It took a little over a year for Ruby to reach <code>1.9.1</code> from <code>1.9.0</code>. This was considered the first “stable” release of the <code>1.9</code> series, as most of the kinks with YARV had been worked out at this point.</p>

<p>There was a lot of work at this time in Ruby around encoding. Before, everything was assumed to be ASCII-ish. The <code>1.9</code> series made encoding into a first class citizen, which including creating the <code>encoding</code> pragma. This ended up becoming a pattern as other pragma were intoduced later (notably <code>frozen_string_literal</code>).</p>

<p>There were a couple of other interesting additions at this time as well. This includes the <code>foo.()</code> operator alias which resolves to the <code>call</code> method. Also introduced were positional arguments that followed a splat argument. Finally we also got block parameters as block variables.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.9.1.txt">EBNF</a></li>
  <li><a href="diagrams/1.9.1.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2009, 9, 26))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby Intermediate Language <small>2009-10-26</small></h2>

<p>In 2009, a team of researchers at the University of Maryland, College Park put together a very interesting project meant to power a type system. It was a Ruby parser written in OCaml that standardized a lot of syntax into a small intermediate representation suitable for further analysis. The researchers (Michael Furr, Jong-hoon An, Jeffrey Foster, and Michael Hicks) presented it at the <a href="http://www.cs.umd.edu/projects/PL/druby/papers/druby-dls09.pdf">2009 ACM conference</a>.</p>

<h4 id="projects">Projects</h4>

<p>This project went on to be a basis of further research projects that were all type systems that took advantage of the same parser, notably:</p>

<ul>
  <li><a href="http://www.cs.umd.edu/projects/PL/druby/">druby</a></li>
  <li><a href="https://www.cs.tufts.edu/~jfoster/papers/oops13.pdf">rtc</a></li>
  <li><a href="http://www.cs.umd.edu/~mwh/papers/rubydust.pdf">rubydust</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2010, 7, 27))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>laser 0.0.1 <small>2010-08-27</small></h2>

<p>An interesting addition to this list is an excerpt from the academic side of Ruby. In 2010 Michael Edgar publishd his undergraduate thesis called <a href="https://github.com/michaeledgar/laser">laser</a> (originally called wool, laser came from lexically- and statically-enriched Ruby). It was a linter, a type system, a documentation generation tool, and more. It featured a plugin system and performed semantic analysis. It was one of the more fully-fledged static analysis tools written for Ruby at this point. It originally parsed Ruby source using regular expressions just to check whitespace but upgraded to <code>ripper</code> eventually to do more complicated analyses.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2011, 2, 22))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>JIS X 3017 <small>2011-03-22</small></h2>

<p>Japanese Standards Association standard <a href="https://standards.globalspec.com/std/1651983/JIS%20X%203017">JIS X 3017</a>.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2011, 9, 31))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 1.9.3 <small>2011-10-31</small></h2>

<p>Two full years later, and Ruby is still in the <code>1.9</code> series. The language itself has completely taken off, due in some part to the popularity of Ruby on Rails, which is now definitively in vogue. For the language itself, not a ton of syntax has changed in this time (a lot of work is being done on the standard library and the shiny new underlying bytecode interpreter). The only thing truly of note at this point is that you can now put trailing commas on method invocations.</p>

<p>This version of Ruby is particularly special for a couple of reasons. The grammar for this version of Ruby ended up being included in a couple of international standards, as Ruby became officially recognized first by the Japanese Standards Association in <a href="https://standards.globalspec.com/std/1651983/JIS%20X%203017">JIS X 3017</a>, and second by the International Organization for Standardization in <a href="https://www.iso.org/obp/ui/#iso:std:iso-iec:30170:ed-1:v1:en">ISO/IEC 30170:2012</a>.</p>

<p>This time period in Ruby’s history is significant in that the influx of new users and the popularity of the language had gotten the attention of some larger companies that were now interested in investing in its future. This resulted in myriad implementations of Ruby being attempted on every platform imaginable, including the Java Virtual Machine, the Parrot Virtual Machine, the Common Language Runtime, and others.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/1.9.3.txt">EBNF</a></li>
  <li><a href="diagrams/1.9.3.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2012, 3, 7))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Topaz <small>2012-04-07</small></h2>

<p>In early 2012, work began on <a href="https://github.com/topazproject/topaz">topaz</a>, an implementation of Ruby targeting RPython. It also took the <code>parse.y</code> file from Ruby, but this time it reimplemented it in python with the grammar rules being written as function decorators.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2012, 3, 15))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>ISO/IEC 30170:2012 <small>2012-04-15</small></h2>

<p>International Organization for Standardization standard <a href="https://www.iso.org/obp/ui/#iso:std:iso-iec:30170:ed-1:v1:en">ISO/IEC 30170:2012</a>.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2013, 1, 24))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 2.0.0 <small>2013-02-24</small></h2>

<p>After another year and a half of development since <code>1.9.3</code>, <code>2.0.0</code> was released. Around this time <code>bugs.ruby-lang.org</code> was introduced as the official bug tracker and so the remaining features on this list can include links to the original discussion. These include:</p>

<ul>
  <li><a href="https://bugs.ruby-lang.org/issues/1102"><code>Module#prepend</code></a><br />
The ability to inject a module into the ancestor chain <em>before</em> the current class so that you could call <code>super</code> to access the original method. This drastically simplified a common construct at the time called <code>alias_method_chain</code>.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/4085">Refinements</a><br />
Another controversial feature that created the <code>using</code> and <code>refine</code> keywords that allowed lexically-scoped monkey-patches.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/4985"><code>%i</code> symbol lists</a><br />
A small but useful addition that expanded the <code>%w</code> pattern to <code>%i</code> to make lists of symbols.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/5474">Keyword arguments</a><br />
Otherwise known as “named” arguments, these were arguments on method calls and definitions that had explicit names. The syntax looked/looks <em>very</em> similar to bare hashes without the braces. So much so that it ended up being implemented using a hash as the final argument to the method call, which caused a fair amount of compatibility problems. This ended up being remedied in <code>3.0</code> a full 8 years later.</li>
</ul>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/2.0.0.txt">EBNF</a></li>
  <li><a href="diagrams/2.0.0.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2013, 3, 15))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>parser 0.9.0 <small>2013-04-15</small></h2>

<p>Around the <code>2.0.0</code> days, Peter Zotov created the <a href="https://github.com/whitequark/parser">parser gem</a>. In the same tradition of other implementations of Ruby, it took the <code>parse.y</code> file from Ruby (and the lexer test suite from Ryan Davis’ <code>ruby_parser</code>) and derived a new parser for creating syntax trees.</p>

<h4 id="links">Links</h4>

<ul>
  <li><a href="projects/parser/README.md.txt">README.md</a></li>
  <li><a href="projects/parser/lib/parser/ruby20.y.txt">lib/parser/ruby20.y</a></li>
</ul>

<h4 id="projects">Projects</h4>

<p>From its humble beginnings, <code>parser</code> ended up getting the attention of a lot of other developers because of its well-documented trees, easy-to-use APIs, and rewriting support. All kinds of other tools ended up being built on top of it, including:</p>

<ul>
  <li><a href="https://github.com/ioquatix/covered">covered</a> - a code coverage reporter</li>
  <li><a href="https://github.com/deep-cover/deep-cover">deep-cover</a> - a code coverage reporter</li>
  <li><a href="https://github.com/Shopify/erb-lint">erb-lint</a> - an ERB file linter</li>
  <li><a href="https://github.com/jonatas/fast">fast</a> - an AST editor</li>
  <li><a href="https://github.com/opal/opal">opal</a> - a Ruby to JavaScript transpiler</li>
  <li><a href="https://github.com/Shopify/packwerk">packwerk</a> - an encapsulation analyzer</li>
  <li><a href="https://github.com/soutaro/querly">querly</a> - a method call finder</li>
  <li><a href="https://github.com/tupl-tufts/rdl">rdl</a> - a type checker</li>
  <li><a href="https://github.com/troessner/reek">reek</a> - a code smell analyzer</li>
  <li><a href="https://github.com/rubocop/rubocop">rubocop</a> - a linter</li>
  <li><a href="https://github.com/emad-elsaid/rubrowser">rubrowser</a> - a module relationship grapher</li>
  <li><a href="https://github.com/YorickPeterse/ruby-lint">ruby-lint</a> - a linter</li>
  <li><a href="https://github.com/ruby-next/ruby-next">ruby-next</a> - a transpiler and polyfill</li>
  <li><a href="https://github.com/victor-am/ruby_detective">ruby_detective</a> - a module relationship grapher</li>
  <li><a href="https://github.com/whitesmith/rubycritic">rubycritic</a> - a code quality reporter</li>
  <li><a href="https://github.com/JoshCheek/seeing_is_believing">seeing_is_believing</a> - an editor intermediate value display</li>
  <li><a href="https://github.com/testdouble/standard">standard</a> - a rubocop wrapper with fewer options</li>
  <li><a href="https://github.com/soutaro/steep">steep</a> - a static type checker</li>
  <li><a href="https://github.com/mbj/unparser">unparser</a> - a code generation from the parser AST</li>
  <li><a href="https://github.com/kddnewton/vernacular">vernacular</a> - a source code manipulation</li>
  <li><a href="https://github.com/tomoasleep/yoda">yoda</a> - a static analyzer and language server</li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2013, 9, 26))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>TruffleRuby <small>2013-10-26</small></h2>

<p>In late 2013, a research team out of Oracle Labs forked JRuby and created <a href="https://github.com/oracle/truffleruby">TruffleRuby</a>, a reimplementation of Ruby on the JVM that used the Graal dynamic compiler and the Truffle AST interpreter framework. As with JRuby, it used the same reengineered parser ported to Java.</p>
  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2013, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 2.1.0 <small>2013-12-25</small></h2>

<p>Starting with Ruby <code>2.1.0</code>, Ruby starts releasing on a very consistent schedule of every Christmas. The changes in this version include:</p>

<ul>
  <li><a href="https://bugs.ruby-lang.org/issues/7701">Required keyword arguments</a><br />
Previously you always had to specify a default value, but this change allowed those values to be omitted.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/8430">Rational and complex literals</a><br />
Rational and Complex already existed as classes, but this allowed syntax like <code>1/2r</code> for creating them without explicitly referencing the class.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/8579">Frozen string literal suffix</a><br />
This is an interesting addition that was temporarily merged and then replaced before this version was released. The proposal was to add an <code>f</code> suffix to strings to make them frozen by default without having to call a method. This is a theme that we’ll see a lot over time as folks continually propose more ways to remove string allocations. This eventually gets obviated by a proposal to <a href="https://bugs.ruby-lang.org/issues/8992">optimize .freeze</a> on strings within the compiler.</li>
</ul>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/2.1.0.txt">EBNF</a></li>
  <li><a href="diagrams/2.1.0.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2014, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 2.2.0 <small>2014-12-25</small></h2>

<p>In Ruby <code>2.2.0</code>, the only large syntax change is that you can now use <a href="https://bugs.ruby-lang.org/issues/4276">dynamic symbol hash keys</a>. This means you can do something like <code>&#123; "foo #&#123;bar&#125;": baz &#125;</code>.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/2.2.0.txt">EBNF</a></li>
  <li><a href="diagrams/2.2.0.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2015, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 2.3.0 <small>2015-12-25</small></h2>

<p>As with <code>2.1.0</code>, there are still ongoing discussions of frozen strings, and we end up settling on the <a href="https://bugs.ruby-lang.org/issues/8976">frozen_string_literal pragma</a> (following in the tradition of the encoding pragma). This allows users to specify that all strings in the file should be frozen by default. This was considered a temporary measure to prepare for an eventual future where all strings in Ruby would be frozen by default (this was also added as a command-line switch). This was promised for Ruby 3, but didn’t end up making it in.</p>

<p>In addition to the pragma, we also got <a href="https://bugs.ruby-lang.org/issues/9098"><code>&lt;&lt;~</code> heredocs</a> that stripped common leading whitespace, and the <a href="https://bugs.ruby-lang.org/issues/11537"><code>&amp;.</code> operator</a> (otherwise known as the “lonely” operator), which only called the method if the receiver was not <code>nil</code>.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/2.3.0.txt">EBNF</a></li>
  <li><a href="diagrams/2.3.0.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2016, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 2.4.0 <small>2016-12-25</small></h2>

<p>Since its addition three years ago, refinements have not quite been adopted in many places. Nevertheless, work continues on them in this release where you can now use <a href="https://bugs.ruby-lang.org/issues/9451">refined methods with the <code>Symbol#to_proc</code></a> syntax. For example, if you were to refine <code>Integer#to_s</code>, you could now write <code>[1, 2, 3].map(&amp;:to_s)</code> and it would function as you would expect.</p>

<p>In addition, we got <a href="https://bugs.ruby-lang.org/issues/4840">top-level return</a>, which was useful in scripts where you wanted to bail from the entire program if some precondition was not met (like a dependency not beig available or not being on the right platform). Finally, you could now use <a href="https://bugs.ruby-lang.org/issues/10617">multiple assignment in a conditional</a>.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/2.4.0.txt">EBNF</a></li>
  <li><a href="diagrams/2.4.0.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2017, 1, 2))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>tree-sitter 0.0.2 <small>2017-02-02</small></h2>

<p>In earlier 2017, work began on <a href="https://github.com/tree-sitter/tree-sitter-ruby">tree-sitter-ruby</a>, bringing Ruby support to the tree-sitter parser generator and incremental parsing library. While not entirely complete in terms of syntax, it’s far enough along to power jump-to-definition and autocomplete tools.</p>

<p>The project itself is written in JavaScript like the other tree-sitter plugins, which makes it ideal to power a language server and VSCode plugin, which is exactly what it does in <a href="https://github.com/rubyide/vscode-ruby">vscode-ruby</a>.</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2017, 1, 26))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>typedruby <small>2017-02-26</small></h2>

<p>Taking the grammar from Ruby 2.4 and a rewrite of the lexer from ruby_parser, <a href="https://github.com/typedruby/typedruby">typedruby</a> was created as a type system written in Rust. It gets a special notation here as it ended up being reused in other C++ projects, notably the <a href="https://sorbet.org/">sorbet</a> type system (which vendors this parser).</p>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2017, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 2.5.0 <small>2017-12-25</small></h2>

<p>Work continues on refinements, as in this release we get <a href="https://bugs.ruby-lang.org/issues/13812">refinements in string interpolations</a>. Also released in this version were <a href="https://bugs.ruby-lang.org/issues/12906"><code>rescue</code> and <code>ensure</code> at the block level</a>, which had been referenced in the ToDo file for quite a few years at this point.</p>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/2.5.0.txt">EBNF</a></li>
  <li><a href="diagrams/2.5.0.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2018, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 2.6.0 <small>2018-12-25</small></h2>

<p>Keeping with their release schedule of every Christmas, Ruby <code>2.6.0</code> was released one year to the day following <code>2.5.0</code>. One of the most interesting additions to history of parsing Ruby came in this version, which was the addition of <a href="https://github.com/ruby/ruby/commit/0f3dcbdf38db6c7fb04ca0833bb1f9af2c3e7ca4">RubyVM::AbstractSyntaxTree</a>. This addition was accidental, it was added as a means of testing another feature that was being added. Unfortunately for the maintainer, <a href="https://bugs.ruby-lang.org/issues/14844">people noticed</a>.</p>

<p><code>RubyVM::AbstractSyntaxTree</code> uses the internal <code>NODE</code> structs to build out an abstract syntax tree, much like many of the projects from the <code>1.6</code> to <code>1.8</code> days. Because it’s written into core Ruby, it necessarily has access to things that other projects don’t, which makes it particular faithful to the syntax. It is both praised and criticized on release, as it means another module that other implementations have to support if it becomes the blessed path for accessing the Ruby parse tree. The discussion continues to this day.</p>

<p>Other syntax additions include:</p>

<ul>
  <li><a href="https://bugs.ruby-lang.org/issues/5400">Flip-flop (deprecated)</a><br />
At this point the <code>flip-flop</code> operator is deprecated, much to the chagrin of the commenters on the linked issue. This deprecation ends up getting reverted in Ruby <code>2.7</code>.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/12912">Endless range</a><br />
Ranges without endings get added to the syntax, which is a nice pairing with the lazy enumerable methods that have recently been merged. This allows things like <code>(0..).lazy.map &#123; |number| number * 2 &#125;.take(10)</code>, for example, to get the first 10 even numbers.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/13770">Non-ASCII constant names</a><br />
Constants in this version can now use non-ASCII characters in their names, which makes for all kinds of fun obfuscated code involving emojis.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/6354">Escape keywords from class/module scope removed</a><br />
An extremely rarely (hopefully) used feature of Ruby was that you could call <code>break</code> within a class and module body. This was effectively a bug, but it’s interesting and included here because syntax is extremely rarely removed from Ruby. This is one of the few exceptions.</li>
</ul>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/2.6.0.txt">EBNF</a></li>
  <li><a href="diagrams/2.6.0.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2019, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 2.7.0 <small>2019-12-25</small></h2>

<p>Ruby <code>2.7.0</code> brought the biggest amount of new syntax to any version of Ruby. It boasts all kinds of interesting changes, including:</p>

<ul>
  <li><a href="https://bugs.ruby-lang.org/issues/5400">Flip-flop (undeprecated)</a><br />
To the cheers of fans of the flip-flop operator, the deprecation was removed.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/13581">Method reference operator (added)</a><br />
The method reference operator <code>.:</code> was added, as a shortcut for accessing a method object like <code>foo.method(:bar)</code>.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/14183">Keyword arguments (warning about hash-based)</a><br />
Since the addition of keyword arguments back in Ruby <code>2.0</code>, they’ve always been backed by an internal hash. That resulted in all kinds of compatibility issues between implementations of Ruby. To simplify things, in <code>3.0</code> they decided to make them “real” arguments instead of using an internal hash structure. To ease the transition, Ruby <code>2.7.0</code> detected when code would break in <code>3.0</code> and warned about that usage.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/14183">No other keywords syntax</a><br />
To define that no other keywords would be allowed on a method call, you could now use the special <code>**nil</code> syntax.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/14799">Beginless range</a><br />
To complement the endless ranges from the previous minor version, ranges could now omit the beginning as well.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/14912">Pattern matching</a><br />
A massive influx of syntax comes in <code>2.7</code> with the introduction of pattern matching. It’s similar to a <code>case..when</code> statement, but instead uses <code>case..in</code> and comes with a whole host of new syntactical constructs. It merits its <a href="https://github.com/ruby/ruby/blob/master/doc/syntax/pattern_matching.rdoc">own documentation page</a> being added to trunk.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/15723">Numbered parameters</a><br />
An interesting addition to this version is numbered parameters. Take a look at the linked issue to see all of the proposed variants. This addition takes inspiration from languages like Scala that support a default block variable.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/15921">Rightward assignment</a><br />
Even before <code>2.7</code> lands, pattern matching gets another addition which is rightward assignment. You can now assign variables using the special <code>=&gt;</code> syntax, as in <code>foo =&gt; bar</code> which assigns to the <code>bar</code> local variable. This adds to the pattern matching because you can now pattern match in rightward assignment.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/16253">Argument forwarding</a><br />
Because keyword arguments are changing so much, its necessary to make a blessed path for forwarding named and unnamed arguments to another method. You can now use the ellipsis operator (<code>...</code>) to send every kind of argument (positional, keyword, and block) over to another method call. This helped eliminate some of the more problematic single-splat usage that was previously being used to accomplish this.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/16275">Method reference operator (removed)</a><br />
Unfortunately, the method reference operator that had been added earlier in the year ended up being reverted. Check the linked issue for the discussion of why.</li>
</ul>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/2.7.0.txt">EBNF</a></li>
  <li><a href="diagrams/2.7.0.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>
<TimelineEntry date={new Date(Date.UTC(2020, 11, 25))}>
  <RubyMarker />
  <TimelineEntryTooltip>
    <h2>Ruby 3.0.0 <small>2020-12-25</small></h2>

<p>Seven years since the release of Ruby <code>2.0</code>, Ruby goes <code>3.0</code>. A lot of changes that don’t have to do with syntax are included in this release. Syntactically, there are a couple of interesting additions:</p>

<ul>
  <li><a href="https://bugs.ruby-lang.org/issues/14183">Keyword arguments (non-hash-based)</a><br />
The <code>3.x</code> version of keyword arguments (as opposed to the hash-based <code>2.x</code> version). This is the feature that Ruby <code>2.7</code> warned about constantly because folks were using the final hash argument to support keyword arguments before.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/16746">Single-line methods</a><br />
Methods can now be written as <code>def foo = bar</code> for more concise syntax.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/16828">Find pattern matching</a><br />
Pattern matching gets another type of pattern called the <code>"find"</code> pattern, which allows you to specify two <code>*</code> operators on each side of the value that you’re searching for.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/17273">shareable_constant_value pragma</a><br />
To better support shared values across ractors, this pragma was added to make constant values shareable without having to freeze them. It’s a <a href="https://docs.ruby-lang.org/en/3.0.0/doc/syntax/comments_rdoc.html#label-shareable_constant_value+Directive">somewhat complicated</a> option that involves a lot of explanation in the linked doc.</li>
  <li><a href="https://bugs.ruby-lang.org/issues/17371"><code>in</code> pattern matching</a><br />
Pattern matching gets one more boost with the ability to use the <code>in</code> operator for a single line. This is similar to rightward assignment, but returns the value of the match.</li>
</ul>

<h4 id="grammar">Grammar</h4>

<ul>
  <li><a href="ebnf/3.0.0.txt">EBNF</a></li>
  <li><a href="diagrams/3.0.0.xhtml">Diagram</a></li>
</ul>

  </TimelineEntryTooltip>
</TimelineEntry>

        </TimelineLine>
      </RubyTimeline>
    </Timeline>
  </div>
);

export default App;
